// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olpvftgnmycofavltxoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9scHZmdGdubXljb2Zhdmx0eG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxODQyMDYsImV4cCI6MjA4Mzc2MDIwNn0.sT-sQq3EzlRt4DREkv5YqE6fUi94s0Z7qW49f0Biopg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});